# Site settings
title: Miao Li
email: miao.li@univ-lille.fr
description: > # this means to ignore newlines until "baseurl:"
  Joint Ph.D. candidate at Université de Lille and KU Leuven of congnitive psychology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://miaoli-psy.github.io/" # the base hostname & protocol for your site
twitter_username: miaolipsy
github_username:  miaoli-psy
linkedin_username: miao-li-1b5476117
# orcid_id:
# google_scholar_id:

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "PhD Candidate of Congnitive Psychology"
excerpt_separator: "<!--more-->"



plugins:
  - jekyll-sitemap
